/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficos;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.IconUIResource;

/**
 *
 * @author juan camilo
 */
public class VentanaEmergente_JOptionPane extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEmergente_JOptionPane
     */
    public VentanaEmergente_JOptionPane() {
        initComponents();
        button_1.addActionListener(new accion_botones());// se pone a la escucha al boton , segun lo que haga la classe "accion_botones"
        button_2.addActionListener(new accion_botones());
        button_3.addActionListener(new accion_botones());
        button_4.addActionListener(new accion_botones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_1 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_1.setText("boton1");

        button_2.setText("boton2");

        button_3.setText("boton3");

        button_4.setText("boton4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(button_1)
                .addGap(18, 18, 18)
                .addComponent(button_2)
                .addGap(27, 27, 27)
                .addComponent(button_3)
                .addGap(18, 18, 18)
                .addComponent(button_4)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_1)
                    .addComponent(button_2)
                    .addComponent(button_3)
                    .addComponent(button_4))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEmergente_JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEmergente_JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEmergente_JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEmergente_JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEmergente_JOptionPane().setVisible(true);
            }
        });
    }
    
    ///////////////////////////////////////////////////////////////////////
     private class accion_botones implements ActionListener{//se crea la clase que ecutara la accion segun el evento

        @Override
        public void actionPerformed(ActionEvent evento) {
            
            if(evento.getActionCommand().equals("boton1")){
            
               // System.out.println("Se preciono el boton1");
                JOptionPane.showMessageDialog(VentanaEmergente_JOptionPane.this/*hace referencia al contenedor padre,si estuviese dentro de un panel ,seia el nombre del panel*/
                        ,"mensaje de \nla ventana","titulo",2/*el numero indica el icono*/);
                
            }else if(evento.getActionCommand().equals("boton2")){
              
                JOptionPane.showInputDialog(VentanaEmergente_JOptionPane.this,"hola mundo","titulo", 3);
                
            }else if(evento.getActionCommand().equals("boton3")){
              
                JOptionPane.showConfirmDialog(VentanaEmergente_JOptionPane.this, "mensage", "titulo",1/*numero de opciones*/, 2/*indica el icono*/);//este retorna un entero segun la respuesta
            
            }else{
                ImageIcon miicono=new ImageIcon("src/graficos/archivo.png");
                
                        
               JOptionPane.showOptionDialog(VentanaEmergente_JOptionPane.this, "mensage","titulo",2, 1,miicono,null ,null);
            }
        }


}
 ////////////////////////////////////////   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    // End of variables declaration//GEN-END:variables
}
